// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJDU1mU-lDNwsY8XdSK32a0r_ZDRl5mEI',
    appId: '1:240390422286:web:3b9560057c1028cbb7a15f',
    messagingSenderId: '240390422286',
    projectId: 'flutter-84f0f',
    authDomain: 'flutter-84f0f.firebaseapp.com',
    databaseURL: 'https://flutter-84f0f-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-84f0f.appspot.com',
    measurementId: 'G-1EEQ0ND63K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2TnmSreGb2PT9-VhKQnOMbIeyrJLxWQM',
    appId: '1:240390422286:android:140a46d3d0b2413bb7a15f',
    messagingSenderId: '240390422286',
    projectId: 'flutter-84f0f',
    databaseURL: 'https://flutter-84f0f-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-84f0f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBX7BnfJALRCkR6Wi5brmORR0lEEmSAGM',
    appId: '1:240390422286:ios:08184c4eaf2d2b9bb7a15f',
    messagingSenderId: '240390422286',
    projectId: 'flutter-84f0f',
    databaseURL: 'https://flutter-84f0f-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-84f0f.appspot.com',
    iosBundleId: 'com.example.practicapushnotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBX7BnfJALRCkR6Wi5brmORR0lEEmSAGM',
    appId: '1:240390422286:ios:08184c4eaf2d2b9bb7a15f',
    messagingSenderId: '240390422286',
    projectId: 'flutter-84f0f',
    databaseURL: 'https://flutter-84f0f-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-84f0f.appspot.com',
    iosBundleId: 'com.example.practicapushnotification',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJDU1mU-lDNwsY8XdSK32a0r_ZDRl5mEI',
    appId: '1:240390422286:web:d38dc8fb297b42cdb7a15f',
    messagingSenderId: '240390422286',
    projectId: 'flutter-84f0f',
    authDomain: 'flutter-84f0f.firebaseapp.com',
    databaseURL: 'https://flutter-84f0f-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-84f0f.appspot.com',
    measurementId: 'G-WDRJY7NL1L',
  );
}
